### ISSUE TITLE
SVG is invalid - some tags end with "d=".

### ISSUE THREAD

**Issue by tabatkins** [mobomo/stately#3]
Some of the `<glyph>` tags in the SVG are incomplete - they're written like `<glyph d=` and just end there.  Obviously, a string is needed for the attribute value, and a closing > character.

**Comment by bpmarkowitz** [comment]
Thanks for the note. Which SVG file?

**Comment by tabatkins** [comment]
The font file, sorry: stately.svg.  It happens in the "usa" and "z" glyphs.

**Comment by bpmarkowitz** [comment]
I think it might have been a formatting issue in the SVG, can you take a look and see if that fixed it?

**Comment by tabatkins** [comment]
Ah, sorry for leaving this here.  You're right - the actual markup is fine.  Maybe it's a problem with how GitHub displays it?  When I copy-paste from the file, I get the proper value.  Anyway, as there's no issue, I'm closing this.
