### ISSUE TITLE
Error in readme example

### ISSUE THREAD

**Issue by delfuego** [mobomo/stately#6]
Howdy -- I _love_ this font and idea, and just started playing around with it! One issue, though: the example in the readme has an error, in that it uses ids for all the &lt;li&gt; items, but then the example CSS uses the title-based selector (.stately li[title="va"]) to style the various states with a new color (rather than an ID-based selector, e.g., ".stately li#va").

Thanks for the awesome font and idea!

**Comment by bpmarkowitz** [comment]
thanks and good catch, that was some old markup.

**Comment by delfuego** [comment]
Wow, that wasn't slow. :)

**Comment by bpmarkowitz** [comment]
You caught me mid-coffee :)
